"""initial

Revision ID: 59a2847680c9
Revises:
Create Date: 2023-07-22 03:30:17.530242
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59a2847680c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    )
    op.create_table(
        'digests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'timestamp',
            postgresql.TIMESTAMP(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_digests_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_digests')),
    )
    op.create_table(
        'posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('popularity', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['subscription_id'],
            ['subscriptions.id'],
            name=op.f('fk_posts_subscription_id_subscriptions'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    )
    op.create_table(
        'users_subscriptions',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['subscription_id'],
            ['subscriptions.id'],
            name=op.f('fk_users_subscriptions_subscription_id_subscriptions'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
            name=op.f('fk_users_subscriptions_user_id_users'),
        ),
        sa.PrimaryKeyConstraint(
            'user_id', 'subscription_id', name=op.f('pk_users_subscriptions')
        ),
    )
    op.create_table(
        'posts_digests',
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('digest_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['digest_id'],
            ['digests.id'],
            name=op.f('fk_posts_digests_digest_id_digests'),
        ),
        sa.ForeignKeyConstraint(
            ['post_id'],
            ['posts.id'],
            name=op.f('fk_posts_digests_post_id_posts'),
        ),
        sa.PrimaryKeyConstraint(
            'post_id', 'digest_id', name=op.f('pk_posts_digests')
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_digests')
    op.drop_table('users_subscriptions')
    op.drop_table('posts')
    op.drop_table('digests')
    op.drop_table('users')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
