"""Rename popularity to rating

Revision ID: 707f513cdf16
Revises: 59a2847680c9
Create Date: 2023-07-23 21:55:34.221888
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707f513cdf16'
down_revision = '59a2847680c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'posts', 'popularity', nullable=False, new_column_name='rating'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'posts', 'rating', nullable=False, new_column_name='popularity'
    )
    # ### end Alembic commands ###
